export const webhookEventOptions = [
  { name: 'Add Image', value: 'add_image' },
  { name: 'Upload', value: 'upload' },
  { name: 'Add Signer', value: 'add_signer' },
  { name: 'Remove Signer', value: 'remove_signer' },
  { name: 'Sign', value: 'sign' },
  { name: 'Close', value: 'close' },
  { name: 'Auto Close', value: 'auto_close' },
  { name: 'Deadline', value: 'deadline' },
  { name: 'Document Closed', value: 'document_closed' },
  { name: 'Cancel', value: 'cancel' },
  { name: 'Update Deadline', value: 'update_deadline' },
  { name: 'Update Auto Close', value: 'update_auto_close' },
  { name: 'Update Locale', value: 'update_locale' },
  { name: 'Custom', value: 'custom' },
  { name: 'Refusal', value: 'refusal' },
  { name: 'Acceptance Term Enqueued', value: 'acceptance_term_enqueued' },
  { name: 'Acceptance Term Sent', value: 'acceptance_term_sent' },
  { name: 'Acceptance Term Completed', value: 'acceptance_term_completed' },
  { name: 'Acceptance Term Refused', value: 'acceptance_term_refused' },
  { name: 'Acceptance Term Canceled', value: 'acceptance_term_canceled' },
  { name: 'Acceptance Term Expired', value: 'acceptance_term_expired' },
  { name: 'Acceptance Term Error', value: 'acceptance_term_error' },
  {
    name: 'Attempts by WhatsApp Exceeded',
    value: 'attempts_by_whatsapp_exceeded',
  },
  {
    name: 'Attempts by Liveness or Facematch Exceeded',
    value: 'attempts_by_liveness_or_facematch_exceeded',
  },
  { name: 'Liveness Refused', value: 'liveness_refused' },
  { name: 'Facematch Refused', value: 'facematch_refused' },
  { name: 'Document Copy Refused', value: 'documentscopy_refused' },
  { name: 'Biometric Refused', value: 'biometric_refused' },
  { name: 'OCR Refused', value: 'ocr_refused' },
  { name: 'Signature Started', value: 'signature_started' },
];
